spring.application.name=urlshortner

# Enable Config Server import (MANDATORY for Spring Boot 2.4+)
spring.config.import=configserver:http://localhost:8888

# Config Server settings
spring.cloud.config.uri=http://localhost:8888
spring.cloud.config.fail-fast=true
